name: Run Python script periodically # ワークフローの名前

on:
  schedule:
    - cron: '0 9,18,24 * * *' # 毎日 9時, 18時, 24時 (UTC) に実行
  workflow_dispatch: # 手動実行を可能にする

jobs:
  run-script:
    runs-on: ubuntu-latest # 実行環境は Ubuntu

    steps:
      - name: Checkout code # コードをリポジトリからチェックアウト
        uses: actions/checkout@v2
      - name: Set up Python # Pythonのセットアップ
        uses: actions/setup-python@v2
        with:
          python-version: '3.9' # Pythonのバージョンを指定
      - name: Install dependencies # 依存関係のインストール
        run: pip install -r requirements.txt # requirements.txt に記述されたライブラリをインストール
      - name: Run script # スクリプトの実行
        run: python main.py # main.py を実行