name: Run Python script periodically # ワークフローの名前

on:
  schedule:
    - cron: '0 0 * * *'  # 日本時間18時（UTC 9時）
    - cron: '0 9 * * *'  # 日本時間3時（UTC 18時）
    - cron: '0 15 * * *'  # 日本時間8時（UTC 23時）
  workflow_dispatch: # 手動実行を可能にする

jobs:
  run-script:
    runs-on: ubuntu-latest # 実行環境は Ubuntu

    steps:
      - name: Checkout code # コードをリポジトリからチェックアウト
        uses: actions/checkout@v2
      - name: Set up Python # Pythonのセットアップ
        uses: actions/setup-python@v2
        with:
          python-version: '3.9' # Pythonのバージョンを指定
      - name: Install dependencies # 依存関係のインストール
        run: pip install -r requirements.txt # requirements.txt に記述されたライブラリをインストール
      - name: Run script # スクリプトの実行
        run: python main.py # main.py を実行