name: Run Python script periodically # ワークフローの名前

on:
  schedule:
    - cron: '0 0 * * *'  # 日本時間18時（UTC 9時）
    - cron: '0 9 * * *'  # 日本時間3時（UTC 18時）
    - cron: '0 15 * * *'  # 日本時間8時（UTC 23時）
  push:
    branches:
      - main  # `main` ブランチに変更があったら実行
  workflow_dispatch:  # 手動実行を可能にする

jobs:
  run_script:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.9'

      - name: Install dependencies
        run: |
          pip install -r requirements.txt

      - name: Run Python script
        env:
          LINE_ACCESS_TOKEN: ${{ secrets.LINE_ACCESS_TOKEN }}
          LINE_SECRET: ${{ secrets.LINE_SECRET }}
          YOUTUBE_API_KEY: ${{ secrets.YOUTUBE_API_KEY }}
          OPENAI_API_KEY: ${{ secrets.OPENAI_API_KEY }}
          LINE_USER_ID: ${{ secrets.LINE_USER_ID }}
        run: python main.py